### ISSUE TITLE
disable sorting of arrays 

### ISSUE THREAD

**Issue by adrian-gierakowski** [SkeLLLa/node-object-hash#15]
I'd like to be able to disable the sorting of arrays, so that `hash([1,2] != hash([2,1])`, while keeping all other "object" types sorted. Is this currently possible?

**Comment by SkeLLLa** [comment]
Hi. Currently it's not supported. But I think it's easy to add such option. 
For example object sorter could consume not only `boolean`, but also an `object` that will define granular sorting behaviour for needed types that are used in `stringifier.*` methods.

It would be non-breaking change, and quiet easy to implement. If you would like to submit a PR, you're welcome. If not, I think I could find some time by the next weekend to add this.

**Comment by adrian-gierakowski** [comment]
thanks, I've added a [`sortArrays` option on my fork](https://github.com/Feeld/node-object-hash/commit/5d108a3747f3445f76a8d15337eb840f47aef870) for now, which I set to `false` to get my desired behaviour, cause that was the quickest way to get what I wanted. But I'll try to submit a PR with your what you've suggested if I find some time later this week.

**Comment by SkeLLLa** [comment]
@adrian-gierakowski good.

**Comment by SkeLLLa** [comment]
If you still interested I've implemented granular sorting control options. The changes aren't published yet, but you may preview them in https://github.com/SkeLLLa/node-object-hash/tree/next branch.

Now it will add possibility to control what kind of items you need to [sort](https://github.com/SkeLLLa/node-object-hash/blob/next/docs/interfaces/objectsorter.sortoptions.md). Also it allows to disable type coercion(https://github.com/SkeLLLa/node-object-hash/blob/next/docs/interfaces/objectsorter.coerceoptions.md).

I think it will be released in near future (~ in a week I think). But that would be v2.0.0.

**Comment by SkeLLLa** [comment]
Version 2.0.0-rc.1 released to npm.You may install it via `npm i node-object-hash@next`
https://www.npmjs.com/package/node-object-hash/v/2.0.0-rc.1

It should contains all features you wanted:
https://github.com/SkeLLLa/node-object-hash/blob/master/docs/interfaces/hasher.hasheroptions.md#optional-sort

https://github.com/SkeLLLa/node-object-hash/blob/master/docs/interfaces/objectsorter.sortoptions.md#optional-array

**Comment by SkeLLLa** [comment]
Released in v2.0.0. Feel free to test and reopen if it doesn't work as expected.
