### ISSUE TITLE
Library fails with ES6 classes

### ISSUE THREAD

**Issue by miatidis-storfund** [SkeLLLa/node-object-hash#16]
Hi,

Let's suppose that I have following ES6 class:

```
class ClassA {
  constructor(public propertyA: string) { 
    this.propertyA = propertyA;
  }
}
```

`obj.constructor.name` returns 'ClassA' and `__guessObjectType()` returns 'unknown'

As a result, all different objects of type ClassA return same hash!

I am not sure how to handle this case, naively I would also return 'object' in default handling of switch in `guessObjectType()`

**Comment by miatidis-storfund** [comment]
The `sortedObjectString()` in _v0/index.js_ seems to work nicely in all cases, but I am not sure why it has been replaced with the `stringifier` version

**Comment by SkeLLLa** [comment]
Hi. In current version the main idea is that objects produced by class constructor should implement `toString` method that return's it's string representation.
Here's similar issue with example:
https://github.com/SkeLLLa/node-object-hash/issues/10

If you have some ideas how to improve this behavior, PRs welcome.

**Comment by SkeLLLa** [comment]
Closing as stale. Feel free to reopen if suggested solution doesn't work.
