### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by mrjjwright** [SkeLLLa/node-object-hash#20]
I am sorry if this comes off as a dumb question but what are some of examples of what you could use this library to do?  I have entertained the idea of hashing my objects into a history tree, similar to git and things like that.   I was curious what others actually use this for.

**Comment by SkeLLLa** [comment]
@mrjjwright this library mostly used to check unique object values. In javascript simple `JSON.stringify` will not guarantee the order of object key-value pairs. Also you may have arrays with identical contents, but placed in different order, e.g. `[1,2]` and `[2,1]`. So this lib performs sorting of such different js object types. Then it transforms all the staff to some string representation and optionally calculates hash of this representation to get small sized hash. Also this lib optionally can perform coercion, e.g. if you have data like `{isActive: 1}` and other `{isActive: true}` those can have identical hashes.
For example it's useful if you have different sources of data and you want to ensure that there will be no duplicates in your database, you may calculate hash, add such field into your document and check if it's unique. And if it's not you may perform something like merge doc, or overwrite.
